### ISSUE TITLE
Issue with bank logs

### ISSUE THREAD

**Issue by ItzKiwiSap** [OmerBenGera/SuperiorSkyblock2#48]
In some of the bank logs, there are a lot of 0's.

![2021-01-27_11 33 31](https://user-images.githubusercontent.com/48173954/106028082-ce422100-60cb-11eb-9e55-404ede23074d.png)

(Requested by Ome_R to create an issue on github)

**Comment by OmerBenGera** [comment]
Hey, show me your menu file please

**Comment by OmerBenGera** [comment]
The issue is probably because you use {4} as a placeholder. There are 3 different placeholders for the amount:
{4} - raw format of the money (aka no format at all)
{5} - formatted money placeholder, which you'll probably want to use
{6} - fancy format for money (adds k, M, etc to the end of the placeholder)

I am closing this for now :)
