### ISSUE TITLE
Not able to use titles in missions

### ISSUE THREAD

**Issue by Nekosity12** [OmerBenGera/SuperiorSkyblock2#6]
I was told to open up an issue so omer wouldn't forget to add a way to implement titles in missions to do something like i.e. pop up a screen on the players message:
"Congratulations
You've sucessfully finished mission <mission_name>!"
(Screenshot of the conversation: https://i.imgur.com/jeRqGOb.png)

**Comment by OmerBenGera** [comment]
Check out build #17 - I added /is admin title. The usage for the command is:
/is admin title <player-name> <fade-in> <duration> <fade-out> -title [message...] -subtitle [message...]

You must include -title and -subtitle (one of them at least) in the command, otherwise it will fail.
There's also /is admin titleall to send a title to all island members, similar to /is admin msgall
