### ISSUE TITLE
Losing all or some of my Island levels after going to the nether

### ISSUE THREAD

**Issue by CS223** [OmerBenGera/SuperiorSkyblock2#73]
Hey, every time a player goes to the nether for the first they lose all of their Island levels or just some. The only thing that I have done that can maybe affect is changing the 'schematic-offset' value in the config.yml to true.

Here is a video showing me what happens after they make it to the nether: https://streamable.com/n3ket7 

As you can see, their island level for some reason goes down.

**Comment by OmerBenGera** [comment]
Weird, when setting it to true, then the level and worth should be subtracted by the values of the schematic blocks.
Let me know how to replicate the issue on another server with default SSB files.

**Comment by CS223** [comment]
So I started a new server with SSB2 (Dev build B59), Essentials, Vault, and Multiverse-Core. Using the default value the only thing I changed was adding the offset setting into the Island creation menu making it true. Then I logged on and made an Island which now had 0 levels then I created a nether portal and went in it and my island levels dropped to negative. After that, I went into the island config and make it so that people can't have negative then reset my island placed some blocks on the island and went to the nether again and lost some island levels again. No errors in console or anything I can see why this would be happing

**Comment by OmerBenGera** [comment]
What about the worth values? Are they okay?

**Comment by CS223** [comment]
On my server, we use shopgui to give the worth but when I was testing yeah it dropped too by a random amount

**Comment by OmerBenGera** [comment]
I found an issue that might cause it - looks like when the schematic of the nether is going beyond the border, its blocks are counted towards the worth, and therefore they are offset as well. However, because they are outside of the border, these blocks aren't counted towards the worth value, and therefore it looks like levels are taken away. This is fixed once you reveal the entire schematic and it fits in your island as a whole. Let me know if that's the case for you as well.
At this moment, I have no idea how this can be "fixed", and at this moment I think it cannot be considered as a bug.

**Comment by CS223** [comment]
Yeah just tested that and no Is level goes down if the whole nether is in the border. So I might just change the schematic or remove the bit that is outside of the Island

**Comment by OmerBenGera** [comment]
Yeah, I think that's the best solution.

**Comment by CS223** [comment]
Edited my previous comment.

**Comment by OmerBenGera** [comment]
It's not something related to a specific schematic. If the schematic is created and part of it is out of the border, the offset will take part of the current worth value, as the part that is outside of the border isn't added to the worth value of the island, however it is to the offset
