### ISSUE TITLE
Island Level Decreases when using Minions from JetsMinions

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#80]
Purpur 1.16.5
SuperiorSkyblock-b68
JetsMinions-6.9.1

https://www.youtube.com/watch?v=Bjr-v4E_vo8

Island level constantly decreases when minions are mining blocks, I spoke with Jet and he said its most likely an issue between Superior and JetsMinions but could not find anything on his end.

What could be done to resolve this?

**Comment by OmerBenGera** [comment]
There should be already support for it, weird.
I am gonna check it out.

**Comment by Skizzles** [comment]
Thank you

**Comment by OmerBenGera** [comment]
Mind sending me a copy of the JetsMinion jar that you have on discord?

**Comment by Skizzles** [comment]
Sent

**Comment by OmerBenGera** [comment]
When a miner breaks a block, the level goes down. However, if the block is placed again, it goes up again. Everything seems to work as it should.

**Comment by Skizzles** [comment]
https://youtu.be/V9LhJXCXI2M

Here is a video of a players island going negative and continuing after the minion is placed again

**Comment by OmerBenGera** [comment]
Are you using the built in system for generators?
Because it doesn't seem like it tells SSB about the new blocks that are generated. Aka, even if you'll break the blocks using a pickaxe, it will still occur

**Comment by Skizzles** [comment]
Yes built in system

**Comment by OmerBenGera** [comment]
Run /is admin debug Action: Block Break, and check if blocks are "broken" twice by the minions.
For me everything works fine and I have no issues whatsoever.

**Comment by Skizzles** [comment]
It breaks once, for some reason it only shows debug for stone tho when the minion is mining it.

Maybe it has something to do with my island levels?

**Comment by OmerBenGera** [comment]
It will only show for blocks that have level/worth (aka blocks that SSB tracks)

**Comment by Skizzles** [comment]
Ah I see, so seems something with how it tracks stone is causing it to decrease?

**Comment by OmerBenGera** [comment]
ahm try using /is admin debug Action: Block Place, check if stone is placed.

**Comment by Skizzles** [comment]
A stone is placed back based off debug.

**Comment by OmerBenGera** [comment]
Weird, so it seems like blocks are counted correctly. Are levels still decrease when no miners are mining?
Because it worked fine for me as well, so it might be another thing causing levels to go down

**Comment by Skizzles** [comment]
With no miners mining it does not, Also seems it does not do that anymore... but now his woodcutters are causing the island level to increase a ton.

https://screenshots.skizzles.me/wAnA3/nEgovufa88.mp4

Idk wtf is going on at this point...

**Comment by OmerBenGera** [comment]
That's because the tree that is grown is counted as SSB knows about trees that generate.
However, Slimefun removes all the logs and leaves, but doesn't let SSB know about it, causing it to not get down.
If slimefun has an event so I can know which blocks are broken, I can fix it on my side - otherwise, they'll have to implement a basic support for SSB so it knows about the blocks that are broken :)

**Comment by OmerBenGera** [comment]
SuperiorSkyblock listens to block changes and calculates block counts in real time. So for example, when you, as a player, break a block, the BlockBreakEvent is fired, so the plugin knows a block was broken and therefore adjusts the counts for that block.
However, when a plugin sets a block, there's no event called unless they call a custom one. Therefore, SuperiorSkyblock can't tell that the block was broken, which causes the counts (and therefore the levels and worth) to be incorrect. /is recalc of course fixes it, but my aim is to add support for as many plugins as possible so the /is recalc is never needed.

Just to note, the /is recalc command isn't a really heavy task anymore, so using it is not a big deal anymore, due to lots of caching, not counting "unused chunks" and more methods to make it as lightweight as possible.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
So I looked into this more with Jet and he gave me a jar to test but the issue is still occurring. So him and I are seeing if its something on his end that can be resolved.

**Comment by OmerBenGera** [comment]
You said the issue with JetsMinions doesn't occur anymore... I talked about the Slimefun issue

**Comment by Skizzles** [comment]
This issue seems on Jet's end and I have been working with him to fix it
