### ISSUE TITLE
Question regarding SuperiorSkyblockAPI and Custom Mission jars

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#86]
So none of the basic Superior mission jars support Slimefun items so we use a custom missions jar to even try and attempt this.... problem is the person who created it is no longer on my team. 

When attempting to decompile the jar it seems like I am missing some depends for the pom file (maven).. I was trying to add the offhand check to this mission jar and also have it support multiple requirements (like the other missions do)

Could you possibly help at all? :) Currently it works except with the offhand items and it only allows 1 requirement...
[SlimefunItemMission.zip](https://github.com/OmerBenGera/SuperiorSkyblock2/files/6020804/SlimefunItemMission.zip)

**Comment by OmerBenGera** [comment]
I don't understand the issue - your mission file doesn't remove items from off hand..?

**Comment by Nekosity12** [comment]
Yes, whenever you submit a quest and is set to consume items it will not consume the item. So players can bypass submitting say an expensive item for a quest that gives a big reward.

However there's also the issue that whenever someone tries to submit the quest and only has one of the requirements set, it will let them. I.E. say the quest requires:
x16 Copper Dust
x16 Iron Dust
The quest will submit if the player has just x16 copper dust or just x16 iron dust.

**Comment by Skizzles** [comment]
Exactly as Neko stated.

**Comment by OmerBenGera** [comment]
I checked the source code, and it happens because the removeItem method of Bukkit doesn't support off hand.
You need to add an additional check for the off hand and remove items from it if necessary.
You can see an example for my version to remove items from off hand as well here:
https://github.com/OmerBenGera/SuperiorSkyblock2-Missions/blob/master/ItemsMissions/src/com/bgsoftware/superiorskyblock/missions/ItemsMissions.java#L220
